version: '3'
services:
  redis-slave1:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - '6379:6379'
    command: redis-server --port 6379 --slaveof 10.0.0.243 6379

    volumes:
      - ./log/redis-server.log:/var/log/redis/redis-server.log
      - ./data:/data
      - ./config/redis-slaves.conf:/usr/local/etc/redis/redis.conf