version: '3'
services:
  redis-slave1:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - '6379:6379'
    command: > 
      bash -c "mkdir -p /var/log/redis && 
      touch /var/log/redis/redis.log && 
      redis-server --port 6379 --slaveof 10.0.0.243 6379  --logfile /var/log/redis/redis.log"

    volumes:
      - ./data:/data
      - ./log-redis:/var/log/redis/redis.log
      - ./config/redis-slaves.conf:/usr/local/etc/redis/redis.conf