version: '3'
services:
  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - '6379:6379'
    command: > 
      bash -c "mkdir -p /data/log && 
      touch /data/log/redis.log && 
      redis-server --port 6379 --slaveof 10.0.0.243 6379  --logfile /data/log/redis.log"

    volumes:
      - ./data:/data
      - ./config/redis-slaves.conf:/usr/local/etc/redis/redis.conf