version: '3'
services:
  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - '6379:6379'
    command: > 
      bash -c "mkdir -p /data/log/redis && 
      touch /data/log/redis/redis.log && 
      redis-server --port 6379 --slaveof 10.0.0.243 6379  --logfile /data/log/redis/redis.log"

    volumes:
      - ./data:/data
      - ./config/redis-slaves.conf:/usr/local/etc/redis/redis.conf

  redis-slave1-sentinel:
    image: redis:latest
    container_name: redis-slave1-sentinel
    ports:
      - "5000:5000"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis-slave1-sentinel/sentinel-slave1.conf:/usr/local/etc/redis/sentinel.conf
    depends_on: 
      - redis-slave1
