version: '3'
services:
  redis-master:
    image: redis:latest
    container_name: redis_master
    volumes:
      - ./data:/data
      - ./config/redis-master.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    command: redis-server