version: '3'
services:
  redis-master:
    image: redis:latest
    container_name: redis_master
    volumes:
      - ./data:/data
      - ./config/redis-master.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    command: > 
      bash -c "mkdir -p /data/log/redis && 
      touch /data/log/redis/redis.log && 
      redis-server --port 6379 --logfile /data/log/redis/redis.log"

  redis-master-sentinel:
    image: redis:latest
    container_name: redis_master_sentinel
    ports:
      - "5000:5000"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis-master-sentinel/redis-master-sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on: 
      - redis-master
